version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - copyloopvar
    - unused
    - unconvert
    - misspell
    - bodyclose
    - revive
    - gocyclo
    - whitespace
    - unparam
    - revive
    - gocritic
    - nolintlint
    - paralleltest
formatters:
  enable:
    - gofmt
    - gci
  exclusions:
    generated: lax
run:
  allow-parallel-runners: true
  tests: true
